### ISSUE TITLE
Migrate to single controller

### ISSUE THREAD

**Issue by antoineco** [triggermesh/knative-sources#43]
Follow the same model as [triggermesh/aws-event-sources](https://github.com/triggermesh/aws-event-sources) for consistency and maintainability.

* [x] Lay down foundation for common controller (#48)
* [x] Include Slack source in controller (#51 #53)
* [x] Include Zendesk source in controller (#52 #54)
* [x] Consolidate reconcilers to use common GenericReconcilers and tests (#58 #61)
